[package]
name = "dev_cleaner_core"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
hashbrown = "0.15.4"
ahash = "0.8.12"
confy = "1.0.0"

owo-colors.workspace = true