[package]
name = "dev_cleaner"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
log.workspace = true
env_logger = "0.11.8"

dev_cleaner_cli = { path = "../dev_cleaner_cli" }
dev_cleaner_gui = { path = "../dev_cleaner_gui" }
